DO $$ DECLARE
  sid UUID := '00000000-0000-0000-0000-000000000001';
  eng_id UUID := '85fd791a-0366-4456-9669-228dbfe87143';
  c10_id UUID := 'aca6ed6e-2263-4841-be61-10db6a280f21';
BEGIN
  INSERT INTO class_subjects (class_id, subject_id) VALUES (c10_id, eng_id) ON CONFLICT DO NOTHING;
  DELETE FROM questions WHERE chapters::text LIKE '%A Hero%' OR chapters::text LIKE '%Grandma Climbs%' OR chapters::text LIKE '%Girl by the Tracks%' OR chapters::text LIKE '%Quality of Mercy%' OR chapters::text LIKE '%Gentleman of Rio%' OR chapters::text LIKE '%I am the Land%' OR chapters::text LIKE '%Dr. B. R. Ambedkar%' OR chapters::text LIKE '%The Song of India%' OR chapters::text LIKE '%The Concert%' OR chapters::text LIKE '%Jazz Poem%' OR chapters::text LIKE '%The Discovery%' OR chapters::text LIKE '%Ballad of the Tempest%' OR chapters::text LIKE '%Colours of Silence%' OR chapters::text LIKE '%The Blind Boy%' OR chapters::text LIKE '%Science and Hope%' OR chapters::text LIKE '%Narayanpur Incident%' OR chapters::text LIKE '%On Top of the World%' OR chapters::text LIKE '%A Great Martyr%' OR chapters::text LIKE '%The Bird of Happiness%';
  INSERT INTO questions (school_id, subject_id, question_type, question_text, options, answer, marks, difficulty, chapters, tags, is_active) VALUES
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Something has bitten me, __________?', '[{"key": "A", "value": "haven''t it", "correct": false}, {"key": "B", "value": "hasn''t it", "correct": true}, {"key": "C", "value": "aren''t it", "correct": false}, {"key": "D", "value": "don''t it", "correct": false}]', 'B', 1, 'easy', '["A Hero"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: It was a frightful proposition for Swami, __________?', '[{"key": "A", "value": "didn''t it", "correct": false}, {"key": "B", "value": "hadn''t it", "correct": false}, {"key": "C", "value": "wasn''t it", "correct": true}, {"key": "D", "value": "don''t it", "correct": false}]', 'C', 1, 'easy', '["A Hero"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Prolonged usage of smart phone creates a lot of health-related problems, __________?', '[{"key": "A", "value": "isn''t it", "correct": false}, {"key": "B", "value": "doesn''t it", "correct": true}, {"key": "C", "value": "does it", "correct": false}, {"key": "D", "value": "is it", "correct": false}]', 'B', 1, 'easy', '["A Hero"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Swami felt cut off from humanity, __________?', '[{"key": "A", "value": "didn''t he", "correct": true}, {"key": "B", "value": "did he", "correct": false}, {"key": "C", "value": "don''t he", "correct": false}, {"key": "D", "value": "does he", "correct": false}]', 'A', 1, 'easy', '["A Hero"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: There are no scorpions, little fellow, __________?', '[{"key": "A", "value": "are there", "correct": true}, {"key": "B", "value": "were there", "correct": false}, {"key": "C", "value": "didn''t there", "correct": false}, {"key": "D", "value": "isn''t there", "correct": false}]', 'A', 1, 'easy', '["A Hero"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause": 
Ravi: Did you get the bus?
Ganesh: Oh! I didn''t.
Ravi: If I had started early, I __________ missed the bus.', '[{"key": "A", "value": "wouldn''t have", "correct": true}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "would have", "correct": false}, {"key": "D", "value": "will have", "correct": false}]', 'A', 1, 'medium', '["A Hero"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Swami''s Father: Have you taught him the importance of courage?
Swami''s Mother: No. He is a little boy.
Swami''s Father: If you had taught him courage, he __________ slept in the office that night.', '[{"key": "A", "value": "wouldn''t have", "correct": false}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "would have", "correct": true}, {"key": "D", "value": "will have", "correct": false}]', 'C', 1, 'medium', '["A Hero"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Swami''s father ordered Swami to sleep in the office that night.', '[{"key": "A", "value": "to sleep", "correct": true}, {"key": "B", "value": "ordered", "correct": false}, {"key": "C", "value": "ordered to", "correct": false}, {"key": "D", "value": "sleep", "correct": false}]', 'A', 1, 'easy', '["A Hero"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Swami''s granny used to tell him a story every night before he slept.', '[{"key": "A", "value": "tell", "correct": false}, {"key": "B", "value": "to tell", "correct": true}, {"key": "C", "value": "used to", "correct": false}, {"key": "D", "value": "slept", "correct": false}]', 'B', 1, 'easy', '["A Hero"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Suma: Excuse me, could you tell me how to get to the library?
Veena: {=Sure, just follow this street and turn left at the next corner. You will reach the library.}', '[{"key": "A", "value": "Asking direction", "correct": false}, {"key": "B", "value": "Giving direction", "correct": true}, {"key": "C", "value": "Giving advice", "correct": false}, {"key": "D", "value": "Seeking advice", "correct": false}]', 'B', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Teacher: {=Students, open your book at page 25. I want all of you to read the first paragraph silently.}
Students: Okay teacher, we are ready.', '[{"key": "A", "value": "making a request", "correct": false}, {"key": "B", "value": "Giving instructions", "correct": true}, {"key": "C", "value": "Giving suggestion", "correct": false}, {"key": "D", "value": "Giving information", "correct": false}]', 'B', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Kiran: {=Could you please pass me the salt?}
Arun: Certainly.
Kiran: Thank you.', '[{"key": "A", "value": "Advising", "correct": false}, {"key": "B", "value": "Suggesting", "correct": false}, {"key": "C", "value": "Requesting", "correct": true}, {"key": "D", "value": "Ordering", "correct": false}]', 'C', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Sudha: Hello Radha! Why are you standing here?
Radha: Hello! I''m waiting for the bus. I''ve to go to the market.
Sudha: {=Come, I will drop you. I''m going that way.}', '[{"key": "A", "value": "offering suggestion", "correct": false}, {"key": "B", "value": "Seeking direction", "correct": false}, {"key": "C", "value": "Offering help", "correct": true}, {"key": "D", "value": "Seeking agreement", "correct": false}]', 'C', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Archana: Good morning, Deepa. {=If you don''t mind, could I use your pen?}
Deepa: Very good morning. Sure, you can.', '[{"key": "A", "value": "Giving direction", "correct": false}, {"key": "B", "value": "Offering help", "correct": false}, {"key": "C", "value": "Seeking permission", "correct": true}, {"key": "D", "value": "Expressing agreement", "correct": false}]', 'C', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Swami: Father, we are admitting elders in our cricket club. Please join our club.
Father: {=We''ll see about that later.}', '[{"key": "A", "value": "Giving direction", "correct": false}, {"key": "B", "value": "Offering help", "correct": false}, {"key": "C", "value": "Accepting invitation", "correct": false}, {"key": "D", "value": "Refusing invitation", "correct": true}]', 'D', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Inspector: Swami, come and join the police when you are grown up.
Swami: {=Certainly yes, sir.}', '[{"key": "A", "value": "Accepting invitation", "correct": true}, {"key": "B", "value": "Giving invitation", "correct": false}, {"key": "C", "value": "Refusing invitation", "correct": false}, {"key": "D", "value": "Disagreeing politely", "correct": false}]', 'A', 1, 'medium', '["A Hero"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'The poet, Ruskin Bond, calls his grandmother a "genius" because', '[{"key": "A", "value": "she could build beautiful tree houses", "correct": false}, {"key": "B", "value": "she had the unusual skill of climbing trees quickly", "correct": true}, {"key": "C", "value": "she knew everything about different types of trees", "correct": false}, {"key": "D", "value": "she advised everyone to plant more trees", "correct": false}]', 'B', 1, 'easy', '["Grandma Climbs a Tree"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The last time the grandmother climbed a tree, she was', '[{"key": "A", "value": "six years old", "correct": false}, {"key": "B", "value": "sixteen years old", "correct": false}, {"key": "C", "value": "sixty-two years old", "correct": true}, {"key": "D", "value": "seventy-two years old", "correct": false}]', 'C', 1, 'easy', '["Grandma Climbs a Tree"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'In the poem "Grandma Climbs a Tree", the phrase "in a trice" suggests that grandmother', '[{"key": "A", "value": "climbed the trees very slowly and carefully", "correct": false}, {"key": "B", "value": "needed a lot of help to climb trees", "correct": false}, {"key": "C", "value": "could climb up trees very quickly", "correct": true}, {"key": "D", "value": "only climbed when she was forced to", "correct": false}]', 'C', 1, 'medium', '["Grandma Climbs a Tree"]', '["vocabulary"]', true),
  (sid, eng_id, 'mcq', 'According to the poem "Grandma Climbs a Tree", the grandmother was happier', '[{"key": "A", "value": "inside a modern lift (elevator)", "correct": false}, {"key": "B", "value": "staying safely on the ground", "correct": false}, {"key": "C", "value": "up in the branches of a tree", "correct": true}, {"key": "D", "value": "spending time in her childhood home", "correct": false}]', 'C', 1, 'easy', '["Grandma Climbs a Tree"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: He could play, __________?', '[{"key": "A", "value": "can he?", "correct": false}, {"key": "B", "value": "could he?", "correct": false}, {"key": "C", "value": "couldn''t he?", "correct": true}, {"key": "D", "value": "can''t he?", "correct": false}]', 'C', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: I cannot do it, __________?', '[{"key": "A", "value": "can I?", "correct": true}, {"key": "B", "value": "can''t I?", "correct": false}, {"key": "C", "value": "Do I?", "correct": false}, {"key": "D", "value": "don''t I?", "correct": false}]', 'A', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: But there was no real damage, __________?', '[{"key": "A", "value": "Is there?", "correct": false}, {"key": "B", "value": "are there?", "correct": false}, {"key": "C", "value": "was there?", "correct": true}, {"key": "D", "value": "wasn''t there?", "correct": false}]', 'C', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: In a few days Roma made a full recovery, __________?', '[{"key": "A", "value": "Is she?", "correct": false}, {"key": "B", "value": "isn''t she?", "correct": false}, {"key": "C", "value": "did she?", "correct": false}, {"key": "D", "value": "didn''t she?", "correct": true}]', 'D', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Student: Sorry madam. I have dropped the glass.
Teacher: If you had handled it carefully, it __________ broken.', '[{"key": "A", "value": "would have", "correct": false}, {"key": "B", "value": "wouldn''t have", "correct": true}, {"key": "C", "value": "would", "correct": false}, {"key": "D", "value": "will", "correct": false}]', 'B', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Akash: Anand, I am going to picnic tomorrow. Will you come?
Anand: Thank you for inviting me. If you had told me earlier, I __________ joined you.', '[{"key": "A", "value": "would have", "correct": true}, {"key": "B", "value": "wouldn''t have", "correct": false}, {"key": "C", "value": "would", "correct": false}, {"key": "D", "value": "will", "correct": false}]', 'A', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Roma Talreja jammed between other women, was trying to find some space.', '[{"key": "A", "value": "jammed", "correct": false}, {"key": "B", "value": "trying to", "correct": false}, {"key": "C", "value": "was trying", "correct": false}, {"key": "D", "value": "to find", "correct": true}]', 'D', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Baleshwar was trying to hold the blood-covered woman.', '[{"key": "A", "value": "was trying", "correct": false}, {"key": "B", "value": "trying to", "correct": false}, {"key": "C", "value": "to hold", "correct": true}, {"key": "D", "value": "covered", "correct": false}]', 'C', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
He got up to find part of his old rubber slipper''s sole torn off as a result of his fall.', '[{"key": "A", "value": "got up", "correct": false}, {"key": "B", "value": "to find", "correct": true}, {"key": "C", "value": "up to", "correct": false}, {"key": "D", "value": "torn off", "correct": false}]', 'B', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Roma Talreja tried to settle in to a corner near the door.', '[{"key": "A", "value": "tried to", "correct": false}, {"key": "B", "value": "to a corner", "correct": false}, {"key": "C", "value": "to settle", "correct": true}, {"key": "D", "value": "settle in to", "correct": false}]', 'C', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Traffic Police: {=Take the girl to Airoli, there''s a hospital there.}
Baleshwar: No. There is a closer place I know of.', '[{"key": "A", "value": "asking direction", "correct": false}, {"key": "B", "value": "giving suggestion", "correct": true}, {"key": "C", "value": "giving an order", "correct": false}, {"key": "D", "value": "making a request", "correct": false}]', 'B', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Baleshwar: How are you now?
Roma: {=Feeling better now. Thank you for saving my life. I am really grateful to you.}', '[{"key": "A", "value": "making a request", "correct": false}, {"key": "B", "value": "giving instructions", "correct": false}, {"key": "C", "value": "expressing gratitude", "correct": true}, {"key": "D", "value": "giving information", "correct": false}]', 'C', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Shalini: {=Hi Roma, how are you now? We''re sorry to hear about the accident.}
Roma: Feeling better now. Thank you very much for visiting me.', '[{"key": "A", "value": "Expressing anger", "correct": false}, {"key": "B", "value": "Showing sympathy", "correct": true}, {"key": "C", "value": "Expressing gratitude", "correct": false}, {"key": "D", "value": "Expressing humour", "correct": false}]', 'B', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Baleshwar: Good morning, Roma, how are you today?
Roma: A lot better Baleshwar. I can''t even imagine what would have happened if you had not come to my help.
Baleshwar: {=I feel it''s our duty to help others in need. I really feel sorry about the accident.}', '[{"key": "A", "value": "Seeking permission", "correct": false}, {"key": "B", "value": "Showing sympathy", "correct": true}, {"key": "C", "value": "Showing disrespect", "correct": false}, {"key": "D", "value": "Expressing disagreement", "correct": false}]', 'B', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Dinesh: Hi, Roma, how is your health right now?
Roma: {=I am fine. It was all God''s grace that I survived. I am very grateful to you for saving my life.}
Dinesh: Yes. He is a real hero.', '[{"key": "A", "value": "Showing sympathy", "correct": false}, {"key": "B", "value": "Showing respect", "correct": false}, {"key": "C", "value": "Expressing gratitude", "correct": true}, {"key": "D", "value": "Expressing surprise", "correct": false}]', 'C', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Baleshwar: I am new to Mumbai, but I''ve noticed that people here are afraid.
Roma: {=Yes, you are right. They fear of getting involved.}', '[{"key": "A", "value": "Expressing agreement", "correct": true}, {"key": "B", "value": "Giving information", "correct": false}, {"key": "C", "value": "Accepting invitation", "correct": false}, {"key": "D", "value": "expressing gratitude", "correct": false}]', 'A', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'The on-duty physician at the small hospital was unable to provide a comprehensive treatment to the young woman because:', '[{"key": "A", "value": "He was not qualified to treat the patient", "correct": false}, {"key": "B", "value": "The hospital lacked the necessary personnel and equipment", "correct": true}, {"key": "C", "value": "The patient arrived too late for medical intervention", "correct": false}, {"key": "D", "value": "Baleshwar insisted on moving her to another facility immediately", "correct": false}]', 'B', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', '"There''s a closer place I know of," said Baleshwar. This statement reveals that Baleshwar''s mindset at that moment was:', '[{"key": "A", "value": "trying to avoid taking responsibility for the woman", "correct": false}, {"key": "B", "value": "calm, collected, and evaluating his options practically", "correct": false}, {"key": "C", "value": "recognizing the urgency of the situation and prioritizing on saving time", "correct": true}, {"key": "D", "value": "trying to find a hospital that was cheap and affordable", "correct": false}]', 'C', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The closest synonym to the word ''lacked'' used in the passage "the facility lacked personnel..." is:', '[{"key": "A", "value": "Sufficed", "correct": false}, {"key": "B", "value": "Defied", "correct": false}, {"key": "C", "value": "Short of", "correct": true}, {"key": "D", "value": "Abounded", "correct": false}]', 'C', 1, 'medium', '["There''s a Girl by the Tracks!"]', '["vocabulary"]', true),
  (sid, eng_id, 'mcq', 'The medical assistance that the young woman received at this first, smaller hospital was:', '[{"key": "A", "value": "A major surgery", "correct": false}, {"key": "B", "value": "Only basic first aid", "correct": true}, {"key": "C", "value": "An X-ray and stitches", "correct": false}, {"key": "D", "value": "Full specialized treatment", "correct": false}]', 'B', 1, 'easy', '["There''s a Girl by the Tracks!"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to the poem "Quality of Mercy", a king''s sceptre represents:', '[{"key": "A", "value": "The spiritual and divine right of a ruler", "correct": false}, {"key": "B", "value": "The worldly, temporary power that brings fear and awe", "correct": true}, {"key": "C", "value": "The absolute mercy and kindness of a king", "correct": false}, {"key": "D", "value": "The decorative beauty of a royal court", "correct": false}]', 'B', 1, 'medium', '["Quality of Mercy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'In the poem "Quality of Mercy", it is said that "mercy is above this sceptred sway" because:', '[{"key": "A", "value": "mercy is a weakness that undermines a king''s power", "correct": false}, {"key": "B", "value": "mercy is more powerful and valuable than temporary earthly authority", "correct": true}, {"key": "C", "value": "a king cannot rule without instilling constant dread", "correct": false}, {"key": "D", "value": "crowns and sceptres are easily lost in battles", "correct": false}]', 'B', 1, 'medium', '["Quality of Mercy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'In the lines describing the sceptre, the word "temporal" means something that is:', '[{"key": "A", "value": "Related to religious or sacred practices", "correct": false}, {"key": "B", "value": "Lasting forever; eternal", "correct": false}, {"key": "C", "value": "Relating to worldly, material, or limited time", "correct": true}, {"key": "D", "value": "Calculated or strictly measured", "correct": false}]', 'C', 1, 'easy', '["Quality of Mercy"]', '["vocabulary"]', true),
  (sid, eng_id, 'mcq', 'Based on the poem "Quality of Mercy", the statement that best captures the contrast intended by the author is:', '[{"key": "A", "value": "A king is only respected when he wears his crown.", "correct": false}, {"key": "B", "value": "Earthly symbols of power command fear, while mercy stands on a higher ground.", "correct": true}, {"key": "C", "value": "True monarchs should discard their sceptres to prove they are merciful.", "correct": false}, {"key": "D", "value": "Fear is a better attribute for a ruler than mercy.", "correct": false}]', 'B', 1, 'medium', '["Quality of Mercy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to the given lines, mercy descends upon the earth:', '[{"key": "A", "value": "Like a sudden, destructive storm", "correct": false}, {"key": "B", "value": "Like a gentle rain falling from heaven", "correct": true}, {"key": "C", "value": "Through force and strict laws", "correct": false}, {"key": "D", "value": "As a heavy burden on the people", "correct": false}]', 'B', 1, 'easy', '["Quality of Mercy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'By stating that mercy is "twice blest", the author intends to say that:', '[{"key": "A", "value": "It requires two people to agree before it can happen.", "correct": false}, {"key": "B", "value": "It offers benefits in both this world and the afterlife.", "correct": false}, {"key": "C", "value": "It brings a dual benefit by rewarding both the person who shows it and the person who receives it.", "correct": true}, {"key": "D", "value": "It can only be granted twice by a powerful ruler.", "correct": false}]', 'C', 1, 'easy', '["Quality of Mercy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'In the first line of the poem "The quality of mercy is not strain''d", the most appropriate meaning of the word "strain''d" is:', '[{"key": "A", "value": "Filtered or purified", "correct": false}, {"key": "B", "value": "Forced or compelled", "correct": true}, {"key": "C", "value": "Stretched to its physical limit", "correct": false}, {"key": "D", "value": "Weakened by effort", "correct": false}]', 'B', 1, 'medium', '["Quality of Mercy"]', '["vocabulary"]', true),
  (sid, eng_id, 'mcq', 'Based on the poem, the best scenario that demonstrates mercy as "mightiest in the mightiest" is:', '[{"key": "A", "value": "A judge imposing the maximum possible legal penalty to show authority.", "correct": false}, {"key": "B", "value": "A powerful ruler choosing to forgive a repentant wrong-doer when they have the absolute power to punish them.", "correct": true}, {"key": "C", "value": "A weak individual yielding to a demand because they have no other choice.", "correct": false}, {"key": "D", "value": "A wealthy merchant demanding full repayment of a debt with interest.", "correct": false}]', 'B', 1, 'hard', '["Quality of Mercy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: The old man hung his head for a moment in thought, __________?', '[{"key": "A", "value": "haven''t he", "correct": false}, {"key": "B", "value": "didn''t he", "correct": true}, {"key": "C", "value": "hasn''t he", "correct": false}, {"key": "D", "value": "isn''t he", "correct": false}]', 'B', 1, 'easy', '["Gentleman of Rio en Medio"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: They had replastered the old house, __________?', '[{"key": "A", "value": "didn''t they", "correct": false}, {"key": "B", "value": "hadn''t they", "correct": true}, {"key": "C", "value": "haven''t they", "correct": false}, {"key": "D", "value": "don''t they", "correct": false}]', 'B', 1, 'easy', '["Gentleman of Rio en Medio"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Let''s go to the market, __________?', '[{"key": "A", "value": "do we", "correct": false}, {"key": "B", "value": "don''t we", "correct": false}, {"key": "C", "value": "shall we", "correct": true}, {"key": "D", "value": "shan''t we", "correct": false}]', 'C', 1, 'easy', '["Gentleman of Rio en Medio"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Read the lesson loudly, __________?', '[{"key": "A", "value": "didn''t you", "correct": false}, {"key": "B", "value": "will you", "correct": true}, {"key": "C", "value": "shall we", "correct": false}, {"key": "D", "value": "don''t we", "correct": false}]', 'B', 1, 'easy', '["Gentleman of Rio en Medio"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Rohini: John, did you bring your camera?
John: Oh! Sorry.
Rohini: It''s Ok.
John: If I had brought my camera, we __________ taken some photographs.', '[{"key": "A", "value": "wouldn''t have", "correct": false}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "would have", "correct": true}, {"key": "D", "value": "will have", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Chitra: You missed the train, didn''t you?
Saina: Yes. I went to the railway station at 10:30 a.m. But the train had left at 10:15 a.m.
Chitra: If you had gone to the station at 10 a.m. you __________ missed the train.', '[{"key": "A", "value": "wouldn''t have", "correct": true}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "would have", "correct": false}, {"key": "D", "value": "will have", "correct": false}]', 'A', 1, 'medium', '["Gentleman of Rio en Medio"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Mala: Kala, you told me on the other day that you would buy a diamond necklace. Did you buy it?
Kala: No Mala, I didn''t buy it. My mother told me she would give some money. If my mother had given me money I __________ bought it.', '[{"key": "A", "value": "will have", "correct": false}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "would have", "correct": true}, {"key": "D", "value": "would not have", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Vinutha: Hello Susheela, you''re a bit down today.
Susheela: Yes Vinutha. We''ve lost the cricket match by just two runs.
Vinutha: If your team would have selected one more fast bowler, your team __________ won the match.', '[{"key": "A", "value": "would have", "correct": true}, {"key": "B", "value": "shall have", "correct": false}, {"key": "C", "value": "will have", "correct": false}, {"key": "D", "value": "wouldn''t have", "correct": false}]', 'A', 1, 'medium', '["Gentleman of Rio en Medio"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Reporter: Sir, what made you choose arts as your career?
Satish: I lost my hearing. And I was left with no other choice but to become an artist. Or else I __________ become an artist.', '[{"key": "A", "value": "would have", "correct": false}, {"key": "B", "value": "will have", "correct": false}, {"key": "C", "value": "wouldn''t have", "correct": true}, {"key": "D", "value": "would", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Narrator: Why did you not agree to take extra money?
Anselmo: If the land belonged to me, I __________ agreed to take extra money.', '[{"key": "A", "value": "wouldn''t have", "correct": false}, {"key": "B", "value": "would have", "correct": true}, {"key": "C", "value": "shouldn''t have", "correct": false}, {"key": "D", "value": "will have", "correct": false}]', 'B', 1, 'medium', '["Gentleman of Rio en Medio"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
The old man: Friend, don''t speak to me in that manner.
Story Teller: Excuse me please. I never meant to hurt you.', '[{"key": "A", "value": "to hurt", "correct": true}, {"key": "B", "value": "speak", "correct": false}, {"key": "C", "value": "meant", "correct": false}, {"key": "D", "value": "meant to", "correct": false}]', 'A', 1, 'easy', '["Gentleman of Rio en Medio"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Ashok: Did you miss the meeting?
Akshay: Yes. I had to attend an emergency at home.', '[{"key": "A", "value": "to attend", "correct": true}, {"key": "B", "value": "had to", "correct": false}, {"key": "C", "value": "attend", "correct": false}, {"key": "D", "value": "missed", "correct": false}]', 'A', 1, 'easy', '["Gentleman of Rio en Medio"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Dhanvi: I am going to the library. Will you join me?
Naina: Sure, I will join you. I have to refer to some books.', '[{"key": "A", "value": "going to", "correct": false}, {"key": "B", "value": "join", "correct": false}, {"key": "C", "value": "to refer", "correct": true}, {"key": "D", "value": "refer to", "correct": false}]', 'C', 1, 'easy', '["Gentleman of Rio en Medio"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Choose the correct infinitive in the following sentence:
Too many people had gathered at the entrance to receive the chief minister.', '[{"key": "A", "value": "gathered", "correct": false}, {"key": "B", "value": "entrance to", "correct": false}, {"key": "C", "value": "to receive", "correct": true}, {"key": "D", "value": "receive", "correct": false}]', 'C', 1, 'easy', '["Gentleman of Rio en Medio"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Manju: Do you have an extra pen? {=Can you lend it to me?}
Ramu: Sure. With pleasure.', '[{"key": "A", "value": "Ordering", "correct": false}, {"key": "B", "value": "Suggesting", "correct": false}, {"key": "C", "value": "Requesting", "correct": true}, {"key": "D", "value": "Advising", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Don Anselmo: It is the price. I don''t need a cent more. {=Do you agree with the price?}
Story Teller: Yes. We have.', '[{"key": "A", "value": "Taking Order", "correct": false}, {"key": "B", "value": "Giving suggestion", "correct": false}, {"key": "C", "value": "Asking opinion", "correct": true}, {"key": "D", "value": "Giving advice", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Paul: Good evening, Sir.
Doctor: Very good evening. What can I do for you ?
Paul: I have a severe burning sensation in my chest. {=What do you think I must do now?}
Doctor: You will have to give up eating junk food.', '[{"key": "A", "value": "Seeking advice", "correct": true}, {"key": "B", "value": "Giving information", "correct": false}, {"key": "C", "value": "Conveying wishes", "correct": false}, {"key": "D", "value": "Giving instruction", "correct": false}]', 'A', 1, 'medium', '["Gentleman of Rio en Medio"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Veena: Excuse me, are you the warden here?
Samhitha: Yes, how can I help you?
Veena: {=Can you tell me what''s the procedure to join my son in the hostel?}', '[{"key": "A", "value": "Seeking permission", "correct": false}, {"key": "B", "value": "Offering help", "correct": false}, {"key": "C", "value": "Seeking information", "correct": true}, {"key": "D", "value": "Seeking help", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Anil: Could you drop me at the railway station?
Rahul: Yes, of course.
Anil: {=Thank you very much.}
Rahul: You are welcome.', '[{"key": "A", "value": "Expressing sympathy", "correct": false}, {"key": "B", "value": "Expressing gratitude", "correct": true}, {"key": "C", "value": "Offering help", "correct": false}, {"key": "D", "value": "Seeking help", "correct": false}]', 'B', 1, 'medium', '["Gentleman of Rio en Medio"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'The changes the narrator''s friends made to the property after moving to Rio en Medio were:', '[{"key": "A", "value": "They built a new house and cut down all the old trees", "correct": false}, {"key": "B", "value": "They replastered the house, pruned trees, and patched the fence", "correct": true}, {"key": "C", "value": "They built a massive boundary wall to keep the children out", "correct": false}, {"key": "D", "value": "They demolished the old house and built a summer resort", "correct": false}]', 'B', 1, 'easy', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The new owners returned to the office "one day" to:', '[{"key": "A", "value": "sign the final property registration papers", "correct": false}, {"key": "B", "value": "pay the remaining balance for the orchard", "correct": false}, {"key": "C", "value": "lodge a complaint against children overrunning their property", "correct": true}, {"key": "D", "value": "invite the narrator to a housewarming party in the summer", "correct": false}]', 'C', 1, 'easy', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'When the new owners told them not to play on the property, the children reacted by:', '[{"key": "A", "value": "becoming aggressive and throwing stones at the house", "correct": false}, {"key": "B", "value": "ignoring them completely and running away crying", "correct": false}, {"key": "C", "value": "apologizing politely and promising never to return", "correct": false}, {"key": "D", "value": "laughing and responding back good-naturedly in Spanish", "correct": true}]', 'D', 1, 'medium', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The time taken by the buyers to purchase the trees individually from the descendants was:', '[{"key": "A", "value": "Most of the following summer", "correct": false}, {"key": "B", "value": "Most of the following winter", "correct": true}, {"key": "C", "value": "Exactly one week", "correct": false}, {"key": "D", "value": "More than two years", "correct": false}]', 'B', 1, 'medium', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The narrator felt "there was nothing we could do" legally regarding the trees, initially because:', '[{"key": "A", "value": "they did not actually pay the full price for the land", "correct": false}, {"key": "B", "value": "Don Anselmo had legally sold the trees to someone else", "correct": false}, {"key": "C", "value": "despite legal ownership, they respected the old man''s generosity and principles", "correct": true}, {"key": "D", "value": "the local court had ruled against the new buyers", "correct": false}]', 'C', 1, 'hard', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The buyers had to purchase the trees individually from:', '[{"key": "A", "value": "Don Anselmo himself", "correct": false}, {"key": "B", "value": "the real estate agents in Rio en Medio", "correct": false}, {"key": "C", "value": "the descendants of Don Anselmo", "correct": true}, {"key": "D", "value": "the local village council", "correct": false}]', 'C', 1, 'medium', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'When he entered the office, the old man was carrying:', '[{"key": "A", "value": "A brand-new walking stick", "correct": false}, {"key": "B", "value": "A regular, fully functional umbrella", "correct": false}, {"key": "C", "value": "The skeleton of a worn-out umbrella", "correct": true}, {"key": "D", "value": "A legal document for the property sale", "correct": false}]', 'C', 1, 'easy', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The narrator describes the old man''s gloves as "old and torn and his fingertips showed through them." This detail primarily highlights Don Anselmo''s:', '[{"key": "A", "value": "extreme carelessness regarding his clothes", "correct": false}, {"key": "B", "value": "poverty despite his dignity and stature", "correct": true}, {"key": "C", "value": "love for wearing fashionable, unique items", "correct": false}, {"key": "D", "value": "intention to look poor to get a better price", "correct": false}]', 'B', 1, 'medium', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', '"...a dark young man with eyes like a gazelle." The figure of speech used in this phrase is:', '[{"key": "A", "value": "Metaphor", "correct": false}, {"key": "B", "value": "Simile", "correct": true}, {"key": "C", "value": "Personification", "correct": false}, {"key": "D", "value": "Alliteration", "correct": false}]', 'B', 1, 'easy', '["Gentleman of Rio en Medio"]', '["figure_of_speech"]', true),
  (sid, eng_id, 'mcq', 'The narrator compares the old man''s coat to a "Prince Albert" coat worn by Senator Catron to:', '[{"key": "A", "value": "emphasize that the old man was a wealthy politician", "correct": false}, {"key": "B", "value": "mock the old man''s poor appearance in front of others", "correct": false}, {"key": "C", "value": "show that despite being faded and old, the coat and the man carried an air of past importance, power, and dignity", "correct": true}, {"key": "D", "value": "indicate that the coat was a direct gift from the Senator", "correct": false}]', 'C', 1, 'hard', '["Gentleman of Rio en Medio"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The figure of speech that is predominantly used in the line "I am the land. I wait" is:', '[{"key": "A", "value": "Simile", "correct": false}, {"key": "B", "value": "Metaphor", "correct": false}, {"key": "C", "value": "Personification", "correct": true}, {"key": "D", "value": "Alliteration", "correct": false}]', 'C', 1, 'easy', '["I am the Land"]', '["figure_of_speech"]', true),
  (sid, eng_id, 'mcq', 'In the poem "I am the Land", the phrase "car lot eyes I stare" suggests that the land is:', '[{"key": "A", "value": "happy to see cars parked on it", "correct": false}, {"key": "B", "value": "being urbanized and commercialized, losing its natural beauty", "correct": true}, {"key": "C", "value": "looking for its new owner", "correct": false}, {"key": "D", "value": "fertile and ready for farming", "correct": false}]', 'B', 1, 'medium', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'In the poem "I am the Land", the repetition of the phrase "I wait" emphasizes the land''s:', '[{"key": "A", "value": "Anger and eagerness to seek revenge", "correct": false}, {"key": "B", "value": "Helplessness and weakness", "correct": false}, {"key": "C", "value": "Patience and ultimate superiority over human greed", "correct": true}, {"key": "D", "value": "Laziness and inability to move", "correct": false}]', 'C', 1, 'easy', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The tone that best describes the speaker''s (the land''s) attitude towards human actions in these lines is:', '[{"key": "A", "value": "Submissive and defeated", "correct": false}, {"key": "B", "value": "Resilient and mockingly patient", "correct": true}, {"key": "C", "value": "Aggressive and violent", "correct": false}, {"key": "D", "value": "Indifferent and uncaring", "correct": false}]', 'B', 1, 'hard', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The poet has used capital letters in the lines "YOU CANNOT PUT A FENCE AROUND THE PLANET EARTH" to:', '[{"key": "A", "value": "point out a mistake made during printing", "correct": false}, {"key": "B", "value": "show that the land is whispering softly", "correct": false}, {"key": "C", "value": "emphasize a strong, powerful statement and challenge human limitations", "correct": true}, {"key": "D", "value": "make the poem look visually unique", "correct": false}]', 'C', 1, 'medium', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The deeper meaning behind the line "You cannot put a fence around the planet Earth" is:', '[{"key": "A", "value": "Earth is too large for man-made fences", "correct": false}, {"key": "B", "value": "Nature and the Earth cannot be bound, divided, or possessed by humans", "correct": true}, {"key": "C", "value": "Fencing material is very expensive", "correct": false}, {"key": "D", "value": "Fences will damage the environment", "correct": false}]', 'B', 1, 'medium', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The tone of the land in the final line "I am the land. I wait." shifts from patience to a feeling of:', '[{"key": "A", "value": "Fear and anxiety", "correct": false}, {"key": "B", "value": "Ultimate triumph and quiet confidence", "correct": true}, {"key": "C", "value": "Helplessness and sadness", "correct": false}, {"key": "D", "value": "Indifference and boredom", "correct": false}]', 'B', 1, 'hard', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The central message or theme conveyed to mankind in the poem "I am the Land" is:', '[{"key": "A", "value": "Humans should buy more land as property.", "correct": false}, {"key": "B", "value": "Fencing is necessary for security and boundaries.", "correct": false}, {"key": "C", "value": "Human pride and ownership are temporary, whereas Nature is eternal and supreme.", "correct": true}, {"key": "D", "value": "The Earth likes to wait for human actions.", "correct": false}]', 'C', 1, 'hard', '["I am the Land"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: He bought books by curtailing his daily needs, __________?', '[{"key": "A", "value": "don''t he", "correct": false}, {"key": "B", "value": "didn''t he", "correct": true}, {"key": "C", "value": "hasn''t he", "correct": false}, {"key": "D", "value": "doesn''t he", "correct": false}]', 'B', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: The Constitution is a fundamental document, __________?', '[{"key": "A", "value": "is it", "correct": false}, {"key": "B", "value": "doesn''t it", "correct": false}, {"key": "C", "value": "isn''t it", "correct": true}, {"key": "D", "value": "wasn''t it", "correct": false}]', 'C', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Chandan: Hey Sneha, have you missed the bus?
Sneha: Yes. I had gone to the bus station at 10:30 AM but the bus had left at 10:15 AM.
Chandan: If you had gone to the bus station at 10:00 AM you __________ missed the bus.', '[{"key": "A", "value": "wouldn''t have", "correct": true}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "will have", "correct": false}, {"key": "D", "value": "would have", "correct": false}]', 'A', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Savitha: Did you go to the Bharatanatyam programme?
Madhura: Yes, I had been with my family. It was fantastic.
Savitha: If you had called me, I __________ joined you.', '[{"key": "A", "value": "should have", "correct": false}, {"key": "B", "value": "wouldn''t have", "correct": false}, {"key": "C", "value": "shouldn''t have", "correct": false}, {"key": "D", "value": "would have", "correct": true}]', 'D', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Mohan: Constitution is not merely to create the organs of the State.
Sohan: Yes. It also limits their authorities.', '[{"key": "A", "value": "merely", "correct": false}, {"key": "B", "value": "to create", "correct": true}, {"key": "C", "value": "organs", "correct": false}, {"key": "D", "value": "limits", "correct": false}]', 'B', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Ashok: Great sages tried to bring all the communities of India together.
Akshay: True.', '[{"key": "A", "value": "to bring", "correct": true}, {"key": "B", "value": "together", "correct": false}, {"key": "C", "value": "widening", "correct": false}, {"key": "D", "value": "keep", "correct": false}]', 'A', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Sujay: I''m suffering from stomach ache since last week.
Vijay: {=Don''t worry. It''ll turn out all right. Why don''t you consult an expert doctor?}', '[{"key": "A", "value": "Giving suggestion", "correct": true}, {"key": "B", "value": "Offering help", "correct": false}, {"key": "C", "value": "Seeking permission", "correct": false}, {"key": "D", "value": "Expressing sympathy", "correct": false}]', 'A', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Tilak: I am doing my post-graduation in English.
Vivek: {=Is it? Could you please teach me some grammatical structures in English language?}', '[{"key": "A", "value": "Request", "correct": true}, {"key": "B", "value": "Advice", "correct": false}, {"key": "C", "value": "Offering help", "correct": false}, {"key": "D", "value": "Giving Acceptance", "correct": false}]', 'A', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Veeranna: {=Suresh, I''m thankful to you for having helped me with English Grammar. I scored good marks in the examination.}
Suresh: That''s alright. It was a revision for me.', '[{"key": "A", "value": "Seeking Help", "correct": false}, {"key": "B", "value": "Expressing Gratitude", "correct": true}, {"key": "C", "value": "Offering Help", "correct": false}, {"key": "D", "value": "Accepting Gratitude", "correct": false}]', 'B', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'A distinct trait that marked Babasaheb throughout his entire life was that:', '[{"key": "A", "value": "He loved traveling around the world", "correct": false}, {"key": "B", "value": "He had a deep interest in attending conferences", "correct": false}, {"key": "C", "value": "He was a voracious reader with an insatiable thirst for books", "correct": true}, {"key": "D", "value": "He had a habit of collecting old antique items", "correct": false}]', 'C', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Babasaheb managed to buy books despite his limited resources by:', '[{"key": "A", "value": "taking loans from international banks", "correct": false}, {"key": "B", "value": "curtailing his own daily needs", "correct": true}, {"key": "C", "value": "receiving books as gifts from friends", "correct": false}, {"key": "D", "value": "working part-time in New York libraries", "correct": false}]', 'B', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'While he was in New York, Babasaheb is said to have purchased:', '[{"key": "A", "value": "32 old books", "correct": false}, {"key": "B", "value": "1,000 old books", "correct": false}, {"key": "C", "value": "2,000 old books", "correct": true}, {"key": "D", "value": "540 old books", "correct": false}]', 'C', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to the text, Dr. Ambedkar bought so many books that they had to be sent to India in 32 boxes:', '[{"key": "A", "value": "During his early school days", "correct": false}, {"key": "B", "value": "While staying permanently in New York", "correct": false}, {"key": "C", "value": "At the time of the Second Round Table Conference in London", "correct": true}, {"key": "D", "value": "Before he started his university education", "correct": false}]', 'C', 1, 'medium', '["Dr. B. R. Ambedkar"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The word "insatiable" in the passage "insatiable thirst for books" means:', '[{"key": "A", "value": "Easily satisfied", "correct": false}, {"key": "B", "value": "Impossible to satisfy", "correct": true}, {"key": "C", "value": "Disinterested or bored", "correct": false}, {"key": "D", "value": "Temporary or brief", "correct": false}]', 'B', 1, 'easy', '["Dr. B. R. Ambedkar"]', '["vocabulary"]', true),
  (sid, eng_id, 'mcq', 'In the poem "The Song of India", the poet speaks of "Epics in Stone", which refers to:', '[{"key": "A", "value": "The modern industrial steel mills", "correct": false}, {"key": "B", "value": "The ancient temples and architectural marvels carved in rock", "correct": true}, {"key": "C", "value": "The books written by freedom fighters", "correct": false}, {"key": "D", "value": "The stories of common people working in fields", "correct": false}]', 'B', 1, 'easy', '["The Song of India"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'When the poet wants to praise the country''s achievements, the Mother asks him to look at the harsh realities like:', '[{"key": "A", "value": "The high-tech dams and clean lakes", "correct": false}, {"key": "B", "value": "The beautiful snow-clad mountains", "correct": false}, {"key": "C", "value": "The beggars, lepers, and ignorant, helpless children", "correct": true}, {"key": "D", "value": "The soldiers guarding the borders", "correct": false}]', 'C', 1, 'easy', '["The Song of India"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to the Mother''s message, a song about the nation:', '[{"key": "A", "value": "should only celebrate future technology", "correct": false}, {"key": "B", "value": "must sing of progress while acknowledging the sorrows and struggles of the people", "correct": true}, {"key": "C", "value": "should focus exclusively on historical wars", "correct": false}, {"key": "D", "value": "must look away from modern industries to focus on nature", "correct": false}]', 'B', 1, 'medium', '["The Song of India"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The "Book of the Morrow", being written by the figure of hope, symbolizes:', '[{"key": "A", "value": "A record of past mistakes made during wars", "correct": false}, {"key": "B", "value": "A diary detailing daily weather patterns", "correct": false}, {"key": "C", "value": "A bright future and destiny that will erase the country''s sorrows", "correct": true}, {"key": "D", "value": "An account book for industrial steel mills", "correct": false}]', 'C', 1, 'medium', '["The Song of India"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The central theme of the dialogue between the Poet and Mother India is:', '[{"key": "A", "value": "A disagreement about which language should be used for national songs", "correct": false}, {"key": "B", "value": "A realization that true patriotism involves celebrating development while actively addressing social evils and poverty", "correct": true}, {"key": "C", "value": "A debate comparing the benefits of agriculture versus heavy machinery", "correct": false}, {"key": "D", "value": "An exploration of why citizens prefer leaving their homeland for other countries", "correct": false}]', 'B', 1, 'hard', '["The Song of India"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Smitha bit her lips in self-reproach, __________?', '[{"key": "A", "value": "does she?", "correct": false}, {"key": "B", "value": "doesn''t she?", "correct": false}, {"key": "C", "value": "didn''t she?", "correct": true}, {"key": "D", "value": "did she?", "correct": false}]', 'C', 1, 'easy', '["The Concert"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: They had come with high hopes, __________?', '[{"key": "A", "value": "hadn''t they?", "correct": false}, {"key": "B", "value": "had they?", "correct": false}, {"key": "C", "value": "did they?", "correct": false}, {"key": "D", "value": "didn''t they?", "correct": true}]', 'D', 1, 'easy', '["The Concert"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: I must hear him and see him, __________?', '[{"key": "A", "value": "must I?", "correct": false}, {"key": "B", "value": "don''t I?", "correct": false}, {"key": "C", "value": "do I?", "correct": false}, {"key": "D", "value": "mustn''t I?", "correct": true}]', 'D', 1, 'easy', '["The Concert"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: We have always done things together, __________?', '[{"key": "A", "value": "have we?", "correct": false}, {"key": "B", "value": "haven''t we?", "correct": true}, {"key": "C", "value": "don''t we?", "correct": false}, {"key": "D", "value": "didn''t we?", "correct": false}]', 'B', 1, 'easy', '["The Concert"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: You must not bother him with such requests, __________?', '[{"key": "A", "value": "do you?", "correct": false}, {"key": "B", "value": "don''t you?", "correct": false}, {"key": "C", "value": "mustn''t you?", "correct": false}, {"key": "D", "value": "must you?", "correct": true}]', 'D', 1, 'easy', '["The Concert"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: He will come tomorrow morning, __________?', '[{"key": "A", "value": "doesn''t he?", "correct": false}, {"key": "B", "value": "won''t he?", "correct": true}, {"key": "C", "value": "does he?", "correct": false}, {"key": "D", "value": "will he?", "correct": false}]', 'B', 1, 'easy', '["The Concert"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the sentence and choose the correct infinitive:
Vinay has decided to write a letter to the chairman.', '[{"key": "A", "value": "has", "correct": false}, {"key": "B", "value": "decided", "correct": false}, {"key": "C", "value": "to write", "correct": true}, {"key": "D", "value": "chairman", "correct": false}]', 'C', 1, 'easy', '["The Concert"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the sentence and choose the correct infinitive:
He was learning to play the sitar.', '[{"key": "A", "value": "to play", "correct": true}, {"key": "B", "value": "was", "correct": false}, {"key": "C", "value": "sitar", "correct": false}, {"key": "D", "value": "learning", "correct": false}]', 'A', 1, 'easy', '["The Concert"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the sentence and choose the correct infinitive:
Smitha had known the frightening truth that Anant was going to die.', '[{"key": "A", "value": "had", "correct": false}, {"key": "B", "value": "was", "correct": false}, {"key": "C", "value": "known", "correct": false}, {"key": "D", "value": "to die", "correct": true}]', 'D', 1, 'easy', '["The Concert"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the sentence and choose the correct infinitive:
He was already able to compose his own tunes to the astonishment of their guru.', '[{"key": "A", "value": "was", "correct": false}, {"key": "B", "value": "to compose", "correct": true}, {"key": "C", "value": "astonishment", "correct": false}, {"key": "D", "value": "able", "correct": false}]', 'B', 1, 'easy', '["The Concert"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the sentence and choose the correct infinitive:
Pedestrians are requested to keep off the grass.', '[{"key": "A", "value": "to keep off", "correct": true}, {"key": "B", "value": "grass", "correct": false}, {"key": "C", "value": "are", "correct": false}, {"key": "D", "value": "requested", "correct": false}]', 'A', 1, 'easy', '["The Concert"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the sentence and choose the correct infinitive:
The people began to move towards the exits.', '[{"key": "A", "value": "began", "correct": false}, {"key": "B", "value": "exits", "correct": false}, {"key": "C", "value": "to move", "correct": true}, {"key": "D", "value": "towards", "correct": false}]', 'C', 1, 'easy', '["The Concert"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Doctor: {="Take him home. Give him the things he likes. Indulge him."}', '[{"key": "A", "value": "Ordering", "correct": false}, {"key": "B", "value": "Advice", "correct": true}, {"key": "C", "value": "Suggestion", "correct": false}, {"key": "D", "value": "giving direction", "correct": false}]', 'B', 1, 'medium', '["The Concert"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Smitha: No, how can I? We''ve always done things together, Ananth and I.
Aunt Sushila: {=''A walk in the park might make you feel better,''}', '[{"key": "A", "value": "suggestion", "correct": true}, {"key": "B", "value": "offering help", "correct": false}, {"key": "C", "value": "seeking permission", "correct": false}, {"key": "D", "value": "inviting", "correct": false}]', 'A', 1, 'medium', '["The Concert"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Vijay: Good morning, Sujay. You look very dull today. May I know the reason?
Sujay: I''m suffering from stomach ache since last week.
Vijay: {=Don''t worry. It''ll turn out all right. Why don''t you consult an expert doctor?}', '[{"key": "A", "value": "Giving suggestion", "correct": true}, {"key": "B", "value": "Offering help", "correct": false}, {"key": "C", "value": "Seeking permission", "correct": false}, {"key": "D", "value": "Expressing sympathy", "correct": false}]', 'A', 1, 'medium', '["The Concert"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Sudha: Hello Radha ! Why are you standing here?
Radha: Hello! I''m waiting for the bus. I''ve to go to the market.
Sudha: {=Come, I will drop you. I''m going that way.}', '[{"key": "A", "value": "Requesting", "correct": false}, {"key": "B", "value": "Seeking direction", "correct": false}, {"key": "C", "value": "Offering help", "correct": true}, {"key": "D", "value": "Agreeing", "correct": false}]', 'C', 1, 'medium', '["The Concert"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and fill in the blank with the correct "if clause":
Rajesh: Hey Sunil ! Did you attend the concert yesterday?
Sunil: No, I didn''t! If you had told me earlier, I __________ attended it.', '[{"key": "A", "value": "would have", "correct": true}, {"key": "B", "value": "wouldn''t have", "correct": false}, {"key": "C", "value": "will have", "correct": false}, {"key": "D", "value": "shall have", "correct": false}]', 'A', 1, 'medium', '["The Concert"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and fill in the blank with the correct "if clause":
Radhika : Hey Smitha! Did you meet Anu yesterday?
Suma: No! It was raining till late at night. Otherwise, I __________ gone to her house.', '[{"key": "A", "value": "wouldn''t have", "correct": false}, {"key": "B", "value": "would have", "correct": true}, {"key": "C", "value": "should have", "correct": false}, {"key": "D", "value": "shouldn''t have", "correct": false}]', 'B', 1, 'medium', '["The Concert"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'The Sitar maestro who was going to perform in Bombay in "The Concert" was:', '[{"key": "A", "value": "Ustad Bismillah Khan", "correct": false}, {"key": "B", "value": "Pandit Ravi Shankar", "correct": true}, {"key": "C", "value": "Pandit Shivkumar Sharma", "correct": false}, {"key": "D", "value": "Ustad Allah Rakha", "correct": false}]', 'B', 1, 'easy', '["The Concert"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The mother tried to tell the girl to keep quiet ("Sh-sh") because:', '[{"key": "A", "value": "She did not want to listen to the musical news", "correct": false}, {"key": "B", "value": "She was busy doing her household chores", "correct": false}, {"key": "C", "value": "She wanted her sick son, Anant, to get enough sleep and rest", "correct": true}, {"key": "D", "value": "She was reading an important book", "correct": false}]', 'C', 1, 'easy', '["The Concert"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to Anant, attending the concert of Pandit Ravi Shankar was "the chance of a lifetime" because:', '[{"key": "A", "value": "tickets were available for free", "correct": false}, {"key": "B", "value": "he wanted to travel around Bombay", "correct": false}, {"key": "C", "value": "he was a great admirer of Pandit Ravi Shankar and played the Sitar himself", "correct": true}, {"key": "D", "value": "his school had sponsored the trip", "correct": false}]', 'C', 1, 'medium', '["The Concert"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Anant''s family moved from Gaganpur to Bombay in order to:', '[{"key": "A", "value": "buy a new house in the city", "correct": false}, {"key": "B", "value": "get treatment for Anant''s cancer at a hospital", "correct": true}, {"key": "C", "value": "attend music concerts every week", "correct": false}, {"key": "D", "value": "admit Anant to a better sports school", "correct": false}]', 'B', 1, 'easy', '["The Concert"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The statement that is TRUE about Anant''s talents, before he fell ill, is:', '[{"key": "A", "value": "He was a singer and a cricket player", "correct": false}, {"key": "B", "value": "He was a talented sitar player, a fast runner, and a top table-tennis player", "correct": true}, {"key": "C", "value": "He was a violinist and a famous painter", "correct": false}, {"key": "D", "value": "He was a writer and loved playing football", "correct": false}]', 'B', 1, 'medium', '["The Concert"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The expressions "wrinkled and weary face" and "unshaven and pain" tell us that the Jazz player:', '[{"key": "A", "value": "is a happy and professional musician", "correct": false}, {"key": "B", "value": "is a pathetic figure, poor, aged, and burdened by life", "correct": true}, {"key": "C", "value": "is getting ready for a big grand concert", "correct": false}, {"key": "D", "value": "wants to hide his real identity from the audience", "correct": false}]', 'B', 1, 'easy', '["Jazz Poem Two"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The musical instrument that the Jazz player holds across his chest in "Jazz Poem Two" is:', '[{"key": "A", "value": "An old Alto Saxophone", "correct": true}, {"key": "B", "value": "A grand acoustic Guitar", "correct": false}, {"key": "C", "value": "A classic wooden Flute", "correct": false}, {"key": "D", "value": "A large brass Trumpet", "correct": false}]', 'A', 1, 'easy', '["Jazz Poem Two"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to the summary of "Jazz Poem Two", the thing that is stuffed inside his run-down shoes is:', '[{"key": "A", "value": "Cotton pads", "correct": false}, {"key": "B", "value": "Thick cloth pieces", "correct": false}, {"key": "C", "value": "Paper", "correct": true}, {"key": "D", "value": "Leather insoles", "correct": false}]', 'C', 1, 'easy', '["Jazz Poem Two"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The dramatic change that happens to the Jazz player during his "transformation through music" is:', '[{"key": "A", "value": "He buys brand new clothes and shoes.", "correct": false}, {"key": "B", "value": "Music releases his spirit, and he becomes a free bird spreading the Black Gospel.", "correct": true}, {"key": "C", "value": "He decides to stop playing the saxophone forever.", "correct": false}, {"key": "D", "value": "He leaves his town to go to another country.", "correct": false}]', 'B', 1, 'medium', '["Jazz Poem Two"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The phrases "faded, sweaty shirt", "loose necktie", and "torn jacket" collectively emphasize the Jazz player''s:', '[{"key": "A", "value": "Rich background", "correct": false}, {"key": "B", "value": "Professional costume choice", "correct": false}, {"key": "C", "value": "Neglected and impoverished physical state", "correct": true}, {"key": "D", "value": "Modern fashion sense", "correct": false}]', 'C', 1, 'medium', '["Jazz Poem Two"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Pepe: Cowards! Coward! {=You will have to kill me first!}
Voices: Out of the way! Devil''s whelp! Lick-spittle!', '[{"key": "A", "value": "making suggestion", "correct": false}, {"key": "B", "value": "Making a request", "correct": false}, {"key": "C", "value": "Seeking information", "correct": false}, {"key": "D", "value": "Ordering", "correct": true}]', 'D', 1, 'medium', '["The Discovery"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: You are an excellent sailor, __________?', '[{"key": "A", "value": "are you?", "correct": false}, {"key": "B", "value": "Aren''t you?", "correct": true}, {"key": "C", "value": "do you?", "correct": false}, {"key": "D", "value": "don''t they?", "correct": false}]', 'B', 1, 'easy', '["The Discovery"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and fill in the blank with the correct "if clause":
Radhika: Hey Suma! Did you meet Anu yesterday?
Suma: No, it was raining till late at night. Otherwise, I __________ gone to her house.', '[{"key": "A", "value": "would not have", "correct": false}, {"key": "B", "value": "would have", "correct": true}, {"key": "C", "value": "should have", "correct": false}, {"key": "D", "value": "should not have", "correct": false}]', 'B', 1, 'medium', '["The Discovery"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and choose the correct infinitive:
Cook: What shall I cook for dinner tonight, sir?
Master: Prepare some special dish. Two guests are going to come for dinner.', '[{"key": "A", "value": "prepare", "correct": false}, {"key": "B", "value": "are going", "correct": false}, {"key": "C", "value": "to come", "correct": true}, {"key": "D", "value": "cook", "correct": false}]', 'C', 1, 'easy', '["The Discovery"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag for the following statement: The captain''s daughter held his hand, __________?', '[{"key": "A", "value": "did she?", "correct": false}, {"key": "B", "value": "didn''t she?", "correct": true}, {"key": "C", "value": "does she?", "correct": false}, {"key": "D", "value": "doesn''t she?", "correct": false}]', 'B', 1, 'easy', '["Ballad of the Tempest"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag for the following statement: The stoutest sails were shattered by the blast, __________?', '[{"key": "A", "value": "weren''t they?", "correct": true}, {"key": "B", "value": "were they?", "correct": false}, {"key": "C", "value": "did they?", "correct": false}, {"key": "D", "value": "didn''t they?", "correct": false}]', 'A', 1, 'easy', '["Ballad of the Tempest"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and choose the correct infinitive:
Sailor 1: The sea is roaring very loudly tonight.
Sailor 2: Yes, it is better to pray for our survival now.', '[{"key": "A", "value": "roaring", "correct": false}, {"key": "B", "value": "is", "correct": false}, {"key": "C", "value": "to pray", "correct": true}, {"key": "D", "value": "survival", "correct": false}]', 'C', 1, 'easy', '["Ballad of the Tempest"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and choose the correct infinitive:
First Mate: The breakers are coming closer to the deck.
Captain: Go downstairs to check the safety of the passengers immediately.', '[{"key": "A", "value": "coming", "correct": false}, {"key": "B", "value": "to check", "correct": true}, {"key": "C", "value": "check", "correct": false}, {"key": "D", "value": "downstairs", "correct": false}]', 'B', 1, 'easy', '["Ballad of the Tempest"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and fill in the blank with the correct "if clause":
Captain: The storm is too severe to handle.
Sailor: If we had anchored the ship in the harbor earlier, we __________ safe from the tempest.', '[{"key": "A", "value": "would be", "correct": false}, {"key": "B", "value": "will be", "correct": false}, {"key": "C", "value": "would have been", "correct": true}, {"key": "D", "value": "can be", "correct": false}]', 'C', 1, 'medium', '["Ballad of the Tempest"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and fill in the blank with the correct "if clause":
Passenger: The storm has finally cleared up this morning.
Crew Member: If the little girl hadn''t spoken so wisely, we __________ all hope last night.', '[{"key": "A", "value": "will lose", "correct": false}, {"key": "B", "value": "would lose", "correct": false}, {"key": "C", "value": "would have lost", "correct": true}, {"key": "D", "value": "had lost", "correct": false}]', 'C', 1, 'medium', '["Ballad of the Tempest"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Little Girl: {="Isn''t God upon the ocean, just the same as on the land?"}
Sailor: Yes, my dear, your words have given us new hope.', '[{"key": "A", "value": "Expressing reassurance / faith", "correct": true}, {"key": "B", "value": "Complaining", "correct": false}, {"key": "C", "value": "Requesting permission", "correct": false}, {"key": "D", "value": "Expressing anger", "correct": false}]', 'A', 1, 'medium', '["Ballad of the Tempest"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Captain: {="Please sit closely together in the darkness and pray."}
Sailor: We will follow your words, captain.', '[{"key": "A", "value": "Expressing gratitude", "correct": false}, {"key": "B", "value": "Making a request / giving a directive", "correct": true}, {"key": "C", "value": "Arguing", "correct": false}, {"key": "D", "value": "Apologizing", "correct": false}]', 'B', 1, 'medium', '["Ballad of the Tempest"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: You want to do this very badly, __________?', '[{"key": "A", "value": "don''t you", "correct": true}, {"key": "B", "value": "didn''t you", "correct": false}, {"key": "C", "value": "do you", "correct": false}, {"key": "D", "value": "aren''t you", "correct": false}]', 'A', 1, 'easy', '["Colours of Silence"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Satish took out his notebook and pencil, __________?', '[{"key": "A", "value": "didn''t he", "correct": true}, {"key": "B", "value": "hadn''t he", "correct": false}, {"key": "C", "value": "did he", "correct": false}, {"key": "D", "value": "does he", "correct": false}]', 'A', 1, 'easy', '["Colours of Silence"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Surender: Satish, why didn''t you come to school today?
Satish: I am not well.
Surender: If you were well, you __________ come to school.', '[{"key": "A", "value": "wouldn''t have", "correct": false}, {"key": "B", "value": "would", "correct": true}, {"key": "C", "value": "would have", "correct": false}, {"key": "D", "value": "will have", "correct": false}]', 'B', 1, 'medium', '["Colours of Silence"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "if clause":
Headmaster: Why don''t you take your son to the school for deaf and dumb children?
Mr. Avtar Narain: My son is not dumb, sir! If my son had become totally dumb, I __________ admitted him to a special school.', '[{"key": "A", "value": "wouldn''t have", "correct": false}, {"key": "B", "value": "would", "correct": false}, {"key": "C", "value": "would have", "correct": true}, {"key": "D", "value": "will have", "correct": false}]', 'C', 1, 'medium', '["Colours of Silence"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Satish''s mother: It has been more than three years since he became ill, how do you possibly think that he can recover his hearing?
Avtar Narain: Why decide that he is going to remain deaf all his life?', '[{"key": "A", "value": "going", "correct": false}, {"key": "B", "value": "to remain", "correct": true}, {"key": "C", "value": "is", "correct": false}, {"key": "D", "value": "do", "correct": false}]', 'B', 1, 'easy', '["Colours of Silence"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Headmaster: We can''t keep your son in our school.
Mr. Avtar Narain: We will have to look for a new school.', '[{"key": "A", "value": "to will", "correct": false}, {"key": "B", "value": "to look", "correct": true}, {"key": "C", "value": "have", "correct": false}, {"key": "D", "value": "can''t", "correct": false}]', 'B', 1, 'easy', '["Colours of Silence"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Avtar Narain: {=If you want to get on in life you have to read a lot. You can learn a great deal of things just by reading.}
Satish: Ok Pitaji, I will.', '[{"key": "A", "value": "seeking information", "correct": false}, {"key": "B", "value": "invitation", "correct": false}, {"key": "C", "value": "request", "correct": false}, {"key": "D", "value": "suggestion", "correct": true}]', 'D', 1, 'medium', '["Colours of Silence"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the given conversation and choose the language function for the underlined sentence:
Surender: {=Satish, why didn''t you come to school today?}
Satish: I am not well.', '[{"key": "A", "value": "order", "correct": false}, {"key": "B", "value": "suggestion", "correct": false}, {"key": "C", "value": "enquiry", "correct": true}, {"key": "D", "value": "advice", "correct": false}]', 'C', 1, 'medium', '["Colours of Silence"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'The Grand Book Exhibition in the advertisement on page 91 is held at:', '[{"key": "A", "value": "City Library", "correct": false}, {"key": "B", "value": "Karnataka Public School, Brahmavara", "correct": true}, {"key": "C", "value": "Town Hall", "correct": false}, {"key": "D", "value": "Community Centre", "correct": false}]', 'B', 1, 'easy', '["The Blind Boy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'According to the poster on page 91, the price of ''English Grammar Made Easy'' is:', '[{"key": "A", "value": "₹300", "correct": false}, {"key": "B", "value": "₹250", "correct": true}, {"key": "C", "value": "₹450", "correct": false}, {"key": "D", "value": "₹600", "correct": false}]', 'B', 1, 'easy', '["The Blind Boy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The book in the exhibition that costs ₹600 is:', '[{"key": "A", "value": "Shakespeare''s Plays", "correct": false}, {"key": "B", "value": "English Poetry Collection", "correct": false}, {"key": "C", "value": "Oxford Advanced Dictionary", "correct": true}, {"key": "D", "value": "Classic English Stories", "correct": false}]', 'C', 1, 'easy', '["The Blind Boy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The rebate offered on all books during this book sale is:', '[{"key": "A", "value": "10%", "correct": false}, {"key": "B", "value": "15%", "correct": false}, {"key": "C", "value": "20%", "correct": true}, {"key": "D", "value": "25%", "correct": false}]', 'C', 1, 'easy', '["The Blind Boy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The free gift given to buyers with every purchase is:', '[{"key": "A", "value": "A pen", "correct": false}, {"key": "B", "value": "A notebook", "correct": false}, {"key": "C", "value": "A bookmark", "correct": true}, {"key": "D", "value": "A bag", "correct": false}]', 'C', 1, 'easy', '["The Blind Boy"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Businessmen, lawyers, and doctors enjoy a much higher income, __________?', '[{"key": "A", "value": "didn''t they?", "correct": false}, {"key": "B", "value": "did they?", "correct": false}, {"key": "C", "value": "do they?", "correct": false}, {"key": "D", "value": "don''t they?", "correct": true}]', 'D', 1, 'easy', '["Science and Hope of Survival"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Choose the appropriate question tag to complete the sentence: Science is an exciting adventure, __________?', '[{"key": "A", "value": "isn''t it?", "correct": true}, {"key": "B", "value": "is it?", "correct": false}, {"key": "C", "value": "was it?", "correct": false}, {"key": "D", "value": "wasn''t it?", "correct": false}]', 'A', 1, 'easy', '["Science and Hope of Survival"]', '["question_tag"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "If clause":
Suman: You look sad. Why are you worried, Tejas?
Tejas: I didn''t get a seat. If I had worked hard, I __________ got the seat in the university.', '[{"key": "A", "value": "would have", "correct": true}, {"key": "B", "value": "wouldn''t have", "correct": false}, {"key": "C", "value": "wouldn''t", "correct": false}, {"key": "D", "value": "would", "correct": false}]', 'A', 1, 'medium', '["Science and Hope of Survival"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and fill in the blank with the correct "If clause":
Suma: Hello Sujatha, You''re a bit down today.
Sujatha: Yes, Suma. We''ve lost the cricket match by just two runs.
Suma: If your team had selected one more fast bowler, your team __________ won the match.', '[{"key": "A", "value": "will have", "correct": false}, {"key": "B", "value": "shall have", "correct": false}, {"key": "C", "value": "wouldn''t have", "correct": false}, {"key": "D", "value": "would have", "correct": true}]', 'D', 1, 'medium', '["Science and Hope of Survival"]', '["if_clause"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Meghana: Hi Arati, will you come to the market? I want to buy vegetables.', '[{"key": "A", "value": "let''s take", "correct": false}, {"key": "B", "value": "come to", "correct": false}, {"key": "C", "value": "to buy", "correct": true}, {"key": "D", "value": "go by", "correct": false}]', 'C', 1, 'easy', '["Science and Hope of Survival"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the conversation and choose the correct infinitive:
Sanjay: Shantha, where are you going now?
Shantha: I''m going to the library to read a novel.', '[{"key": "A", "value": "going to", "correct": false}, {"key": "B", "value": "are you", "correct": false}, {"key": "C", "value": "am going", "correct": false}, {"key": "D", "value": "to read", "correct": true}]', 'D', 1, 'easy', '["Science and Hope of Survival"]', '["infinitives"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and choose the language function for the underlined sentence:
Ganesh: It''s cloudy, we can''t play.
Gouri: {=Yeah, it may rain today.}', '[{"key": "A", "value": "Predicting", "correct": false}, {"key": "B", "value": "Advising", "correct": false}, {"key": "C", "value": "Requesting", "correct": false}, {"key": "D", "value": "Possibility", "correct": true}]', 'D', 1, 'medium', '["Science and Hope of Survival"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'Read the following conversation and choose the language function for the underlined sentence:
Mahesh: Hi, Good morning. How are you?
Suresh: I am not feeling well.
Mahesh: {=Oh, shall I drop you to the hospital?}
Suresh: That''ll be great.', '[{"key": "A", "value": "Expressing ability", "correct": false}, {"key": "B", "value": "Seeking permission", "correct": false}, {"key": "C", "value": "Giving an order", "correct": false}, {"key": "D", "value": "Offering help", "correct": true}]', 'D', 1, 'medium', '["Science and Hope of Survival"]', '["language_function"]', true),
  (sid, eng_id, 'mcq', 'In a fire emergency, the first action to be taken according to the Fire Safety Precautions is to:', '[{"key": "A", "value": "Hide in a room", "correct": false}, {"key": "B", "value": "Raise the alarm and inform others", "correct": true}, {"key": "C", "value": "Use the elevator", "correct": false}, {"key": "D", "value": "Return to collect belongings", "correct": false}]', 'B', 1, 'easy', '["Science and Hope of Survival"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The emergency service that must be called immediately during a fire is the:', '[{"key": "A", "value": "Police", "correct": false}, {"key": "B", "value": "Ambulance", "correct": false}, {"key": "C", "value": "Fire Service", "correct": true}, {"key": "D", "value": "Postal Service", "correct": false}]', 'C', 1, 'easy', '["Science and Hope of Survival"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Elevators must not be used during a fire evacuation because:', '[{"key": "A", "value": "They are too slow", "correct": false}, {"key": "B", "value": "They may stop working and trap people", "correct": true}, {"key": "C", "value": "They are expensive to operate", "correct": false}, {"key": "D", "value": "They make a loud noise", "correct": false}]', 'B', 1, 'medium', '["Science and Hope of Survival"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'If there is heavy smoke in the building, you should:', '[{"key": "A", "value": "Run quickly through the smoke", "correct": false}, {"key": "B", "value": "Stand near windows to breathe", "correct": false}, {"key": "C", "value": "Cover your nose and mouth and crawl low close to the floor", "correct": true}, {"key": "D", "value": "Use the elevator to escape quickly", "correct": false}]', 'C', 1, 'medium', '["Science and Hope of Survival"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'After evacuating during a fire accident, it is safe to re-enter a building:', '[{"key": "A", "value": "Immediately after the visible flames stop", "correct": false}, {"key": "B", "value": "When your friends tell you it is safe", "correct": false}, {"key": "C", "value": "Only after the authorities declare it is safe", "correct": true}, {"key": "D", "value": "Whenever you want to go back in", "correct": false}]', 'C', 1, 'medium', '["Science and Hope of Survival"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The students in Narayanpur continued their silent procession despite the heavy rains because:', '[{"key": "A", "value": "They wanted to reach home quickly", "correct": false}, {"key": "B", "value": "They were determined to express their patriotism peacefully", "correct": true}, {"key": "C", "value": "They wanted to avoid the police", "correct": false}, {"key": "D", "value": "They were participating in a village festival", "correct": false}]', 'B', 1, 'medium', '["Narayanpur Incident"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Students carrying Mahatma Gandhiji''s portrait during the procession symbolised:', '[{"key": "A", "value": "Respect for their school education", "correct": false}, {"key": "B", "value": "Faith in non-violence and truth", "correct": true}, {"key": "C", "value": "Celebration of a local festival", "correct": false}, {"key": "D", "value": "A traditional religious ceremony", "correct": false}]', 'B', 1, 'medium', '["Narayanpur Incident"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The story "Narayanpur Incident" conveys the message to readers that:', '[{"key": "A", "value": "Violence is the best way to solve problems", "correct": false}, {"key": "B", "value": "Unity and courage can overcome difficulties and oppression", "correct": true}, {"key": "C", "value": "Wealth brings ultimate happiness", "correct": false}, {"key": "D", "value": "People should avoid public gatherings", "correct": false}]', 'B', 1, 'medium', '["Narayanpur Incident"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The Narayanpur Incident is considered an inspiring event because:', '[{"key": "A", "value": "It shows the students'' commitment to the freedom movement despite challenges", "correct": true}, {"key": "B", "value": "It describes a village celebration", "correct": false}, {"key": "C", "value": "It teaches modern farming methods", "correct": false}, {"key": "D", "value": "It focuses on children''s games and play", "correct": false}]', 'A', 1, 'medium', '["Narayanpur Incident"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The quality of the participants that is most highlighted in "Narayanpur Incident" is:', '[{"key": "A", "value": "Carelessness", "correct": false}, {"key": "B", "value": "Determination and patriotism", "correct": true}, {"key": "C", "value": "Laziness", "correct": false}, {"key": "D", "value": "Fearfulness", "correct": false}]', 'B', 1, 'medium', '["Narayanpur Incident"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The values that are best reflected in Dicky Dolma''s successful climb to the top of Mount Everest are:', '[{"key": "A", "value": "Greed and laziness", "correct": false}, {"key": "B", "value": "Determination and perseverance", "correct": true}, {"key": "C", "value": "Laziness and pride", "correct": false}, {"key": "D", "value": "Pride and greed", "correct": false}]', 'B', 1, 'easy', '["On Top of the World"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The biographical lesson of Dicky Dolma inspires the readers mainly to:', '[{"key": "A", "value": "Avoid difficult and challenging situations", "correct": false}, {"key": "B", "value": "Depend only on others for their success", "correct": false}, {"key": "C", "value": "Face life''s challenges with courage and confidence", "correct": true}, {"key": "D", "value": "Compete aggressively with everyone", "correct": false}]', 'C', 1, 'easy', '["On Top of the World"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'What emotion does Dicky Dolma experience upon reaching the summit of Mount Everest?', '[{"key": "A", "value": "Jealousy", "correct": false}, {"key": "B", "value": "Anger", "correct": false}, {"key": "C", "value": "Joy and a sense of absolute fulfilment", "correct": true}, {"key": "D", "value": "Fear", "correct": false}]', 'C', 1, 'medium', '["On Top of the World"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The theme most effectively conveyed in "On Top of the World" is:', '[{"key": "A", "value": "The importance of having luxury in life", "correct": false}, {"key": "B", "value": "The power of determination in achieving one''s dreams", "correct": true}, {"key": "C", "value": "The beauty of city life and modernization", "correct": false}, {"key": "D", "value": "The value of competition in sports", "correct": false}]', 'B', 1, 'medium', '["On Top of the World"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'A vital lesson that the readers learn from the author''s journey in "On Top of the World" is:', '[{"key": "A", "value": "Success comes naturally without any effort", "correct": false}, {"key": "B", "value": "Dreams can be achieved through courage, preparation, and persistence", "correct": true}, {"key": "C", "value": "Failure should always be avoided at all costs", "correct": false}, {"key": "D", "value": "Difficult goals are ultimately impossible to achieve", "correct": false}]', 'B', 1, 'medium', '["On Top of the World"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Lieutenant Haneef Uddin chose to join the Indian Army primarily to:', '[{"key": "A", "value": "earn a high salary", "correct": false}, {"key": "B", "value": "serve and protect the nation", "correct": true}, {"key": "C", "value": "travel around the world", "correct": false}, {"key": "D", "value": "continue his family business", "correct": false}]', 'B', 1, 'easy', '["A Great Martyr Ever Cherished"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Haneef Uddin''s supreme sacrifice during the Kargil War reveals that:', '[{"key": "A", "value": "He was ambitious for fame and awards", "correct": false}, {"key": "B", "value": "He valued personal comfort above everything else", "correct": false}, {"key": "C", "value": "He possessed exceptional courage and patriotism", "correct": true}, {"key": "D", "value": "He was unwilling to face major life challenges", "correct": false}]', 'C', 1, 'medium', '["A Great Martyr Ever Cherished"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Haneef Uddin is remembered as a great martyr because:', '[{"key": "A", "value": "He became a famous politician after his service", "correct": false}, {"key": "B", "value": "He sacrificed his life while defending the country during war", "correct": true}, {"key": "C", "value": "He wrote several books about the Indian Army", "correct": false}, {"key": "D", "value": "He won an international music award", "correct": false}]', 'B', 1, 'easy', '["A Great Martyr Ever Cherished"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The message that the lesson "A Great Martyr Ever Cherished" conveys is:', '[{"key": "A", "value": "Wealth is the key to all success", "correct": false}, {"key": "B", "value": "Patriotism and selfless service deserve respect and remembrance", "correct": true}, {"key": "C", "value": "War should always be encouraged", "correct": false}, {"key": "D", "value": "Success depends only on luck and circumstance", "correct": false}]', 'B', 1, 'medium', '["A Great Martyr Ever Cherished"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Lieutenant Haneef Uddin inspires the readers the most with his qualities of:', '[{"key": "A", "value": "Courage, dedication, and love for the nation", "correct": true}, {"key": "B", "value": "Desire for popularity and social status", "correct": false}, {"key": "C", "value": "Interest in adventure sports and hobbies", "correct": false}, {"key": "D", "value": "Preference for a luxurious and comfortable life", "correct": false}]', 'A', 1, 'easy', '["A Great Martyr Ever Cherished"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Wangjia decided to set out on a difficult journey to find the Bird of Happiness:', '[{"key": "A", "value": "To become famous across Tibet", "correct": false}, {"key": "B", "value": "To help the suffering and impoverished people of his village", "correct": true}, {"key": "C", "value": "To find a hidden ancient treasure", "correct": false}, {"key": "D", "value": "To prove his physical strength to the elders", "correct": false}]', 'B', 1, 'easy', '["The Bird of Happiness"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'To show courage while facing the three old monsters, Wangjia:', '[{"key": "A", "value": "ran away from them as fast as possible", "correct": false}, {"key": "B", "value": "asked the village warriors to fight for him", "correct": false}, {"key": "C", "value": "faced them fearlessly and refused to perform their cruel tasks", "correct": true}, {"key": "D", "value": "gave up his journey and returned to his home", "correct": false}]', 'C', 1, 'medium', '["The Bird of Happiness"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The quality of Wangjia that inspires the readers the most is:', '[{"key": "A", "value": "Selfishness", "correct": false}, {"key": "B", "value": "Greed", "correct": false}, {"key": "C", "value": "Laziness", "correct": false}, {"key": "D", "value": "Bravery and determination", "correct": true}]', 'D', 1, 'easy', '["The Bird of Happiness"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'Wangjia''s journey and final success teach us that:', '[{"key": "A", "value": "We should think only about our own self-interest", "correct": false}, {"key": "B", "value": "We should act with courage and kindness for the welfare of others", "correct": true}, {"key": "C", "value": "We should avoid difficult situations to remain happy", "correct": false}, {"key": "D", "value": "We should expect massive rewards for every good deed", "correct": false}]', 'B', 1, 'medium', '["The Bird of Happiness"]', '["comprehension"]', true),
  (sid, eng_id, 'mcq', 'The statement that best describes Wangjia''s character is:', '[{"key": "A", "value": "He was a brave and kind-hearted boy who risked his life to bring happiness to others", "correct": true}, {"key": "B", "value": "He was easily terrified of every small challenge", "correct": false}, {"key": "C", "value": "He wanted only wealth and personal power", "correct": false}, {"key": "D", "value": "He depended entirely on others to help him complete tasks", "correct": false}]', 'A', 1, 'medium', '["The Bird of Happiness"]', '["comprehension"]', true);
END $$;
