DO $$ DECLARE
  gk_id UUID;
  sid UUID := '00000000-0000-0000-0000-000000000001';
BEGIN
  INSERT INTO subjects (id, name, code, school_id)
  VALUES (gen_random_uuid(), 'General Knowledge', 'GK', sid)
  ON CONFLICT DO NOTHING;

  SELECT id INTO gk_id FROM subjects WHERE code = 'GK' AND deleted_at IS NULL LIMIT 1;

  INSERT INTO class_subjects (class_id, subject_id)
  SELECT c.id, gk_id FROM classes c WHERE c.deleted_at IS NULL
  ON CONFLICT DO NOTHING;

  INSERT INTO questions (school_id, subject_id, question_type, question_text, options, answer, marks, difficulty, chapters, tags, is_active) VALUES
  (sid, gk_id, 'mcq', 'What is the capital of Karnataka?',
    '[{"key":"A","value":"Bengaluru","correct":true},{"key":"B","value":"Mysuru","correct":false},{"key":"C","value":"Mangaluru","correct":false},{"key":"D","value":"Hubballi","correct":false}]',
    'A', 1, 'easy', '["States and Capitals"]', '["india","capitals","karnataka"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Maharashtra?',
    '[{"key":"A","value":"Pune","correct":false},{"key":"B","value":"Mumbai","correct":true},{"key":"C","value":"Nagpur","correct":false},{"key":"D","value":"Nashik","correct":false}]',
    'B', 1, 'easy', '["States and Capitals"]', '["india","capitals","maharashtra"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Tamil Nadu?',
    '[{"key":"A","value":"Chennai","correct":true},{"key":"B","value":"Coimbatore","correct":false},{"key":"C","value":"Madurai","correct":false},{"key":"D","value":"Salem","correct":false}]',
    'A', 1, 'easy', '["States and Capitals"]', '["india","capitals","tamil nadu"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Gujarat?',
    '[{"key":"A","value":"Surat","correct":false},{"key":"B","value":"Ahmedabad","correct":false},{"key":"C","value":"Gandhinagar","correct":true},{"key":"D","value":"Rajkot","correct":false}]',
    'C', 1, 'easy', '["States and Capitals"]', '["india","capitals","gujarat"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Rajasthan?',
    '[{"key":"A","value":"Jaipur","correct":true},{"key":"B","value":"Jodhpur","correct":false},{"key":"C","value":"Udaipur","correct":false},{"key":"D","value":"Ajmer","correct":false}]',
    'A', 1, 'easy', '["States and Capitals"]', '["india","capitals","rajasthan"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of West Bengal?',
    '[{"key":"A","value":"Darjeeling","correct":false},{"key":"B","value":"Kolkata","correct":true},{"key":"C","value":"Siliguri","correct":false},{"key":"D","value":"Asansol","correct":false}]',
    'B', 1, 'easy', '["States and Capitals"]', '["india","capitals","west bengal"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Uttar Pradesh?',
    '[{"key":"A","value":"Lucknow","correct":true},{"key":"B","value":"Varanasi","correct":false},{"key":"C","value":"Agra","correct":false},{"key":"D","value":"Noida","correct":false}]',
    'A', 1, 'easy', '["States and Capitals"]', '["india","capitals","uttar pradesh"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Goa?',
    '[{"key":"A","value":"Margao","correct":false},{"key":"B","value":"Panaji","correct":true},{"key":"C","value":"Vasco da Gama","correct":false},{"key":"D","value":"Mapusa","correct":false}]',
    'B', 1, 'easy', '["States and Capitals"]', '["india","capitals","goa"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Madhya Pradesh?',
    '[{"key":"A","value":"Bhopal","correct":true},{"key":"B","value":"Indore","correct":false},{"key":"C","value":"Jabalpur","correct":false},{"key":"D","value":"Gwalior","correct":false}]',
    'A', 1, 'medium', '["States and Capitals"]', '["india","capitals","madhya pradesh"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Bihar?',
    '[{"key":"A","value":"Gaya","correct":false},{"key":"B","value":"Patna","correct":true},{"key":"C","value":"Muzaffarpur","correct":false},{"key":"D","value":"Bhagalpur","correct":false}]',
    'B', 1, 'medium', '["States and Capitals"]', '["india","capitals","bihar"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Punjab?',
    '[{"key":"A","value":"Amritsar","correct":false},{"key":"B","value":"Ludhiana","correct":false},{"key":"C","value":"Chandigarh","correct":true},{"key":"D","value":"Jalandhar","correct":false}]',
    'C', 1, 'medium', '["States and Capitals"]', '["india","capitals","punjab"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Kerala?',
    '[{"key":"A","value":"Kochi","correct":false},{"key":"B","value":"Thiruvananthapuram","correct":true},{"key":"C","value":"Kozhikode","correct":false},{"key":"D","value":"Thrissur","correct":false}]',
    'B', 1, 'medium', '["States and Capitals"]', '["india","capitals","kerala"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Andhra Pradesh?',
    '[{"key":"A","value":"Hyderabad","correct":false},{"key":"B","value":"Vijayawada","correct":false},{"key":"C","value":"Visakhapatnam","correct":false},{"key":"D","value":"Amaravati","correct":true}]',
    'D', 1, 'medium', '["States and Capitals"]', '["india","capitals","andhra pradesh"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Telangana?',
    '[{"key":"A","value":"Hyderabad","correct":true},{"key":"B","value":"Warangal","correct":false},{"key":"C","value":"Karimnagar","correct":false},{"key":"D","value":"Nizamabad","correct":false}]',
    'A', 1, 'medium', '["States and Capitals"]', '["india","capitals","telangana"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Odisha?',
    '[{"key":"A","value":"Bhubaneswar","correct":true},{"key":"B","value":"Cuttack","correct":false},{"key":"C","value":"Puri","correct":false},{"key":"D","value":"Rourkela","correct":false}]',
    'A', 1, 'medium', '["States and Capitals"]', '["india","capitals","odisha"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Jharkhand?',
    '[{"key":"A","value":"Jamshedpur","correct":false},{"key":"B","value":"Ranchi","correct":true},{"key":"C","value":"Dhanbad","correct":false},{"key":"D","value":"Bokaro","correct":false}]',
    'B', 1, 'medium', '["States and Capitals"]', '["india","capitals","jharkhand"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Chhattisgarh?',
    '[{"key":"A","value":"Raipur","correct":true},{"key":"B","value":"Bilaspur","correct":false},{"key":"C","value":"Durg","correct":false},{"key":"D","value":"Korba","correct":false}]',
    'A', 1, 'medium', '["States and Capitals"]', '["india","capitals","chhattisgarh"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Assam?',
    '[{"key":"A","value":"Guwahati","correct":false},{"key":"B","value":"Dispur","correct":true},{"key":"C","value":"Silchar","correct":false},{"key":"D","value":"Dibrugarh","correct":false}]',
    'B', 1, 'hard', '["States and Capitals"]', '["india","capitals","assam"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Uttarakhand?',
    '[{"key":"A","value":"Dehradun","correct":true},{"key":"B","value":"Haridwar","correct":false},{"key":"C","value":"Haldwani","correct":false},{"key":"D","value":"Roorkee","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","uttarakhand"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Himachal Pradesh?',
    '[{"key":"A","value":"Shimla","correct":true},{"key":"B","value":"Manali","correct":false},{"key":"C","value":"Dharamshala","correct":false},{"key":"D","value":"Kullu","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","himachal pradesh"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Haryana?',
    '[{"key":"A","value":"Gurgaon","correct":false},{"key":"B","value":"Faridabad","correct":false},{"key":"C","value":"Chandigarh","correct":true},{"key":"D","value":"Panipat","correct":false}]',
    'C', 1, 'hard', '["States and Capitals"]', '["india","capitals","haryana"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Sikkim?',
    '[{"key":"A","value":"Gangtok","correct":true},{"key":"B","value":"Namchi","correct":false},{"key":"C","value":"Gyalshing","correct":false},{"key":"D","value":"Rangpo","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","sikkim"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Arunachal Pradesh?',
    '[{"key":"A","value":"Itanagar","correct":true},{"key":"B","value":"Tawang","correct":false},{"key":"C","value":"Naharlagun","correct":false},{"key":"D","value":"Pasighat","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","arunachal pradesh"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Manipur?',
    '[{"key":"A","value":"Imphal","correct":true},{"key":"B","value":"Thoubal","correct":false},{"key":"C","value":"Churachandpur","correct":false},{"key":"D","value":"Bishnupur","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","manipur"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Meghalaya?',
    '[{"key":"A","value":"Shillong","correct":true},{"key":"B","value":"Tura","correct":false},{"key":"C","value":"Jowai","correct":false},{"key":"D","value":"Nongstoin","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","meghalaya"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Nagaland?',
    '[{"key":"A","value":"Kohima","correct":true},{"key":"B","value":"Dimapur","correct":false},{"key":"C","value":"Mokokchung","correct":false},{"key":"D","value":"Tuensang","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","nagaland"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Mizoram?',
    '[{"key":"A","value":"Aizawl","correct":true},{"key":"B","value":"Lunglei","correct":false},{"key":"C","value":"Saitual","correct":false},{"key":"D","value":"Champhai","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","mizoram"]', true),
  (sid, gk_id, 'mcq', 'What is the capital of Tripura?',
    '[{"key":"A","value":"Agartala","correct":true},{"key":"B","value":"Udaipur","correct":false},{"key":"C","value":"Dharmanagar","correct":false},{"key":"D","value":"Kailashahar","correct":false}]',
    'A', 1, 'hard', '["States and Capitals"]', '["india","capitals","tripura"]', true);
END $$;
